import type { AdminTemplateDef } from './types';

export const ADMIN_NOTIFICATION_TEMPLATES = {
  'admin.order.new_placed': {
    category: 'orders',
    title: 'New order {orderNumber}',
    description: 'A customer placed a new order. Review it in the orders queue.',
    icon: 'ShoppingCart',
    severity: 'info',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.order.high_value_placed': {
    category: 'orders',
    title: 'High-value order placed',
    description: 'An order with unusually high value was placed and may need attention.',
    icon: 'DollarSign',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.order.cancelled': {
    category: 'orders',
    title: 'Order cancelled',
    description: 'An order was cancelled. Check inventory and payment reconciliation.',
    icon: 'Ban',
    severity: 'warning',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.order.delayed': {
    category: 'orders',
    title: 'Order delayed',
    description: 'Fulfillment or delivery is behind schedule for an order.',
    icon: 'Clock',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.order.refund_request_created': {
    category: 'orders',
    title: 'Refund request created',
    description: 'A customer opened a refund request that needs review.',
    icon: 'RefreshCw',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.order.return_request_created': {
    category: 'orders',
    title: 'Return request created',
    description: 'A return request was submitted and awaits processing.',
    icon: 'RotateCcw',
    severity: 'info',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.order.delivery_issue_reported': {
    category: 'orders',
    title: 'Delivery issue reported',
    description: 'A delivery problem was reported for an order or shipment.',
    icon: 'Truck',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.customer.new_registered': {
    category: 'customers',
    title: 'New customer registered',
    description: 'A new shopper account was created on the marketplace.',
    icon: 'UserPlus',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard'],
  },
  'admin.customer.complaint_submitted': {
    category: 'customers',
    title: 'Customer complaint submitted',
    description: 'A complaint was filed and may require escalation.',
    icon: 'AlertTriangle',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.customer.support_ticket_opened': {
    category: 'customers',
    title: 'Support ticket opened',
    description: 'A new support ticket is waiting in the queue.',
    icon: 'MessageSquare',
    severity: 'info',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.customer.product_reported': {
    category: 'customers',
    title: 'Product reported',
    description: 'A customer reported a listing for policy or quality review.',
    icon: 'Flag',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.customer.refund_requested': {
    category: 'customers',
    title: 'Customer requested refund',
    description: 'A refund was requested outside the standard flow or needs approval.',
    icon: 'CreditCard',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.customer.suspicious_activity': {
    category: 'customers',
    title: 'Suspicious customer activity',
    description: 'Unusual behavior was detected on a customer account.',
    icon: 'ShieldAlert',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.product.pending_approval': {
    category: 'products',
    title: 'New product pending approval',
    description: 'A vendor submitted a product that needs moderation.',
    icon: 'Package',
    severity: 'info',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.product.reported': {
    category: 'products',
    title: 'Product reported',
    description: 'A listing was flagged and should be reviewed.',
    icon: 'Flag',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.product.out_of_stock': {
    category: 'products',
    title: 'Product out of stock',
    description: 'A tracked SKU or listing is now out of stock.',
    icon: 'PackageX',
    severity: 'warning',
    priority: 'medium',
    channels: ['dashboard'],
  },
  'admin.product.duplicate_detected': {
    category: 'products',
    title: 'Duplicate product detected',
    description: 'The system found a possible duplicate listing.',
    icon: 'Copy',
    severity: 'warning',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.product.fake_suspected': {
    category: 'products',
    title: 'Fake product suspected',
    description: 'A listing may violate authenticity rules and needs urgent review.',
    icon: 'ShieldAlert',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.payment.failed': {
    category: 'payments',
    title: 'Payment failed',
    description: 'A customer payment attempt failed at checkout or renewal.',
    icon: 'CreditCard',
    severity: 'danger',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.payment.refund_processed': {
    category: 'payments',
    title: 'Refund processed',
    description: 'A refund was completed in the finance system.',
    icon: 'CheckCircle2',
    severity: 'success',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.payment.large_transaction': {
    category: 'payments',
    title: 'Large transaction detected',
    description: 'A payment exceeded your configured threshold and was flagged.',
    icon: 'TrendingUp',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.payment.daily_sales_target_reached': {
    category: 'payments',
    title: 'Daily sales target reached',
    description: 'Today’s gross sales crossed the configured daily goal.',
    icon: 'Target',
    severity: 'success',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.payment.vendor_payout_requested': {
    category: 'payments',
    title: 'Vendor payout requested',
    description: 'A vendor requested a payout that needs approval or processing.',
    icon: 'Coins',
    severity: 'info',
    priority: 'medium',
    channels: ['dashboard', 'email'],
  },
  'admin.payment.vendor_payout_completed': {
    category: 'payments',
    title: 'Vendor payout completed',
    description: 'A vendor payout was marked as paid.',
    icon: 'CheckCircle2',
    severity: 'success',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.system.server_downtime': {
    category: 'system',
    title: 'Server downtime detected',
    description: 'Health checks indicate the app or API may be unavailable.',
    icon: 'Server',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.system.high_cpu': {
    category: 'system',
    title: 'High CPU usage',
    description: 'Infrastructure CPU usage is above the safe threshold.',
    icon: 'Cpu',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.system.low_storage': {
    category: 'system',
    title: 'Low storage warning',
    description: 'Disk or database storage is running low.',
    icon: 'HardDrive',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.system.backup_completed': {
    category: 'system',
    title: 'Backup completed',
    description: 'Scheduled backup finished successfully.',
    icon: 'Database',
    severity: 'success',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.security.failed_login_attempts': {
    category: 'system',
    title: 'Failed login attempts',
    description: 'Multiple failed sign-ins were detected for an admin or staff account.',
    icon: 'Lock',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.security.too_many_otp': {
    category: 'system',
    title: 'Too many OTP requests',
    description: 'OTP generation rate suggests abuse or a misconfigured client.',
    icon: 'KeySquare',
    severity: 'warning',
    priority: 'high',
    channels: ['dashboard', 'email'],
  },
  'admin.system.sms_failure': {
    category: 'system',
    title: 'SMS service failure',
    description: 'The SMS provider returned errors or is unreachable.',
    icon: 'PhoneOff',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.system.email_failure': {
    category: 'system',
    title: 'Email service failure',
    description: 'Transactional email delivery is failing or deferred.',
    icon: 'MailX',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.security.alert': {
    category: 'system',
    title: 'Security alert',
    description: 'A security rule triggered — review logs and access controls.',
    icon: 'ShieldAlert',
    severity: 'danger',
    priority: 'urgent',
    channels: ['dashboard', 'email', 'sms'],
  },
  'admin.report.daily_sales_ready': {
    category: 'reports',
    title: 'Daily sales summary ready',
    description: 'The daily sales summary report is available.',
    icon: 'BarChart3',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.report.weekly_sales_ready': {
    category: 'reports',
    title: 'Weekly sales report ready',
    description: 'Weekly consolidated sales data is ready to review.',
    icon: 'LineChart',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.report.monthly_marketplace_ready': {
    category: 'reports',
    title: 'Monthly marketplace performance ready',
    description: 'Monthly marketplace KPIs and trends are published.',
    icon: 'PieChart',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.report.campaign_performance_ready': {
    category: 'reports',
    title: 'Campaign performance report ready',
    description: 'Marketing campaign results are ready for analysis.',
    icon: 'Megaphone',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
  'admin.report.most_viewed_products_ready': {
    category: 'reports',
    title: 'Most viewed products report ready',
    description: 'Traffic and view metrics for top products are available.',
    icon: 'Eye',
    severity: 'info',
    priority: 'low',
    channels: ['dashboard', 'email'],
  },
} as const satisfies Record<string, AdminTemplateDef>;

export type AdminEventKey = keyof typeof ADMIN_NOTIFICATION_TEMPLATES;
