import type { CustomerTemplateDef } from './types';

/** Default copy & channel hints for customer notifications. Server code uses these when inserting rows. */
export const CUSTOMER_NOTIFICATION_TEMPLATES = {
  'order.placed_successfully': {
    category: 'orders',
    title: 'Order {orderNumber} placed successfully',
    description: 'We received your order and will confirm payment shortly.',
    icon: 'PackageCheck',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.payment_confirmed': {
    category: 'orders',
    title: 'Payment confirmed',
    description: 'Your payment was successful. The seller can now process your order.',
    icon: 'CreditCard',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.accepted': {
    category: 'orders',
    title: 'Order accepted',
    description: 'Your order has been accepted and is being prepared.',
    icon: 'CheckCircle2',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.packed': {
    category: 'orders',
    title: 'Order packed',
    description: 'Your items have been packed and are ready to ship.',
    icon: 'Box',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'order.shipped': {
    category: 'orders',
    title: 'Order shipped',
    description: 'Your package is on the way. Track it from your orders page.',
    icon: 'Truck',
    severity: 'info',
    channels: ['in_app', 'push', 'email', 'sms'],
  },
  'order.out_for_delivery': {
    category: 'orders',
    title: 'Out for delivery',
    description: 'Your order is out for delivery and should arrive soon.',
    icon: 'Truck',
    severity: 'info',
    channels: ['in_app', 'push', 'email', 'sms'],
  },
  'order.delivered_successfully': {
    category: 'orders',
    title: 'Delivered successfully',
    description: 'Your order was delivered. We hope you enjoy your purchase.',
    icon: 'Package',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.cancelled': {
    category: 'orders',
    title: 'Order cancelled',
    description: 'Your order has been cancelled. Any eligible refund will be processed.',
    icon: 'Ban',
    severity: 'warning',
    channels: ['in_app', 'push', 'email'],
  },
  'order.refund_initiated': {
    category: 'orders',
    title: 'Refund initiated',
    description: 'A refund has been started for your order. Funds may take a few days to appear.',
    icon: 'RefreshCw',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'order.refund_completed': {
    category: 'orders',
    title: 'Refund completed',
    description: 'Your refund has been completed.',
    icon: 'CheckCircle2',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.return_approved': {
    category: 'orders',
    title: 'Return request approved',
    description: 'Your return request was approved. Follow the instructions in your order details.',
    icon: 'RotateCcw',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'order.return_rejected': {
    category: 'orders',
    title: 'Return request rejected',
    description: 'Your return request could not be approved. See details for more information.',
    icon: 'XCircle',
    severity: 'danger',
    channels: ['in_app', 'push', 'email'],
  },
  'payment.successful': {
    category: 'payments',
    title: 'Payment successful',
    description: 'Your payment went through successfully.',
    icon: 'CreditCard',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'payment.failed': {
    category: 'payments',
    title: 'Payment failed',
    description: 'We could not process your payment. Try again or use another method.',
    icon: 'CreditCard',
    severity: 'danger',
    channels: ['in_app', 'push', 'email', 'sms'],
  },
  'payment.cod_confirmed': {
    category: 'payments',
    title: 'Cash on delivery confirmed',
    description: 'Your cash on delivery order is confirmed. Please have the exact amount ready.',
    icon: 'Banknote',
    severity: 'info',
    channels: ['in_app', 'sms'],
  },
  'payment.wallet_credited': {
    category: 'payments',
    title: 'Wallet credited',
    description: 'Your wallet balance has been updated with a new credit.',
    icon: 'Wallet',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'payment.wallet_debited': {
    category: 'payments',
    title: 'Wallet debited',
    description: 'A purchase or adjustment was made using your wallet balance.',
    icon: 'Wallet',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'payment.invoice_available': {
    category: 'payments',
    title: 'Invoice available',
    description: 'Your invoice is ready to download from your order or account area.',
    icon: 'FileText',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'account.created': {
    category: 'account',
    title: 'Welcome — account created',
    description: 'Your Suuqsade account is ready. Explore deals and track orders anytime.',
    icon: 'UserPlus',
    severity: 'success',
    channels: ['in_app', 'email'],
  },
  'account.email_verified': {
    category: 'account',
    title: 'Email verified',
    description: 'Your email address has been verified successfully.',
    icon: 'Mail',
    severity: 'success',
    channels: ['in_app', 'email'],
  },
  'account.phone_verified': {
    category: 'account',
    title: 'Phone verified',
    description: 'Your phone number has been verified successfully.',
    icon: 'Smartphone',
    severity: 'success',
    channels: ['in_app', 'sms'],
  },
  'account.password_changed': {
    category: 'account',
    title: 'Password changed',
    description: 'Your password was updated. If this was not you, contact support immediately.',
    icon: 'KeyRound',
    severity: 'warning',
    channels: ['in_app', 'email', 'sms'],
  },
  'account.login_new_device': {
    category: 'account',
    title: 'Login from new device',
    description: 'We noticed a sign-in from a new device or browser.',
    icon: 'MonitorSmartphone',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'account.login_suspicious': {
    category: 'account',
    title: 'Suspicious login detected',
    description: 'Unusual sign-in activity was detected on your account. Please review security settings.',
    icon: 'ShieldAlert',
    severity: 'danger',
    channels: ['in_app', 'email', 'sms'],
  },
  'account.otp_sent': {
    category: 'account',
    title: 'OTP sent',
    description: 'A one-time code was sent to your registered contact. Do not share it with anyone.',
    icon: 'KeySquare',
    severity: 'info',
    channels: ['sms', 'email'],
  },
  'account.password_reset_requested': {
    category: 'account',
    title: 'Password reset requested',
    description: 'Someone requested a password reset. If it was not you, secure your account.',
    icon: 'KeyRound',
    severity: 'warning',
    channels: ['email', 'sms'],
  },
  'account.password_reset_successful': {
    category: 'account',
    title: 'Password reset successful',
    description: 'Your password was reset. You can now sign in with your new password.',
    icon: 'CheckCircle2',
    severity: 'success',
    channels: ['in_app', 'email'],
  },
  'wishlist.back_in_stock': {
    category: 'wishlist',
    title: 'Wishlist item back in stock',
    description: 'An item you saved is available again. Grab it before it sells out.',
    icon: 'Heart',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'wishlist.price_dropped': {
    category: 'wishlist',
    title: 'Price dropped',
    description: 'A wishlist product is now at a lower price.',
    icon: 'TrendingDown',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'product.low_stock': {
    category: 'wishlist',
    title: 'Low stock',
    description: 'An item you follow is running low. Order soon to avoid missing out.',
    icon: 'AlertTriangle',
    severity: 'warning',
    channels: ['in_app', 'push'],
  },
  'product.out_of_stock': {
    category: 'wishlist',
    title: 'Out of stock',
    description: 'A product you viewed or saved is currently unavailable.',
    icon: 'PackageX',
    severity: 'warning',
    channels: ['in_app', 'email'],
  },
  'product.similar_available': {
    category: 'wishlist',
    title: 'Similar products available',
    description: 'We found products similar to what you were browsing.',
    icon: 'Sparkles',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'product.recently_viewed_discounted': {
    category: 'wishlist',
    title: 'Recently viewed product discounted',
    description: 'A product you recently viewed is now on sale.',
    icon: 'Percent',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'promotion.flash_sale_started': {
    category: 'promotions',
    title: 'Flash sale started',
    description: 'A limited-time flash sale is live. Shop before it ends.',
    icon: 'Zap',
    severity: 'success',
    channels: ['in_app', 'push', 'email', 'sms'],
  },
  'promotion.coupon_received': {
    category: 'promotions',
    title: 'Coupon received',
    description: 'You have a new coupon. Apply it at checkout to save.',
    icon: 'Ticket',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'promotion.coupon_expiring_soon': {
    category: 'promotions',
    title: 'Coupon expiring soon',
    description: 'One of your coupons is about to expire. Use it before you lose it.',
    icon: 'Timer',
    severity: 'warning',
    channels: ['in_app', 'push', 'email'],
  },
  'promotion.new_campaign': {
    category: 'promotions',
    title: 'New campaign available',
    description: 'Check out the latest marketplace offers and collections.',
    icon: 'Megaphone',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'promotion.free_delivery': {
    category: 'promotions',
    title: 'Free delivery campaign',
    description: 'Enjoy free or reduced delivery on eligible orders for a limited time.',
    icon: 'Truck',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
  },
  'promotion.seasonal': {
    category: 'promotions',
    title: 'Seasonal promotion',
    description: 'Seasonal deals are here. Browse curated picks and savings.',
    icon: 'Calendar',
    severity: 'info',
    channels: ['in_app', 'email'],
  },
  'support.ticket_replied': {
    category: 'support',
    title: 'Support ticket replied',
    description: 'Support has added a new reply to your ticket.',
    icon: 'MessageSquare',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'support.review_reminder': {
    category: 'support',
    title: 'Review reminder',
    description: 'How was your order? Your feedback helps other shoppers.',
    icon: 'Star',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'support.seller_replied_to_review': {
    category: 'support',
    title: 'Seller replied to your review',
    description: 'A seller responded to a review you left.',
    icon: 'MessageCircle',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'support.return_request_updated': {
    category: 'support',
    title: 'Return request updated',
    description: 'There is an update on your return or refund request.',
    icon: 'RotateCcw',
    severity: 'info',
    channels: ['in_app', 'push', 'email'],
  },
  'support.delivery_delayed': {
    category: 'support',
    title: 'Delivery delayed',
    description: 'Your delivery is taking longer than expected. We will keep you updated.',
    icon: 'Clock',
    severity: 'warning',
    channels: ['in_app', 'push', 'email', 'sms'],
  },
} as const satisfies Record<string, CustomerTemplateDef>;

export type CustomerEventKey = keyof typeof CUSTOMER_NOTIFICATION_TEMPLATES;
